# Usa una imagen base de Amazon Corretto 22
FROM amazoncorretto:22.0.1

WORKDIR /app

COPY target/*.jar app.jar

ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_NAME=$DB_NAME
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
ENV JWT_SECRET=$JWT_SECRET
ENV EMAIL_SPAM_STATUS=$EMAIL_SPAM_STATUS
ENV EMAIL_TARGET_EMAIL=$EMAIL_TARGET_EMAIL
ENV SCHEDULED_HOUR_CRON=$SCHEDULED_HOUR_CRON

EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
