spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: Baseline
    baselineOnMigrate: true
    migrate-at-startup: true
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  jackson:
    serialization:
      indent_output: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.jpa.repository.query: DEBUG
debug: true

server:
  port: ${SERVER_PORT}

springfox:
  documentation:
    swagger-ui:
      enabled: true

# OpenAPI Properties
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

email:
  spam-status: ${EMAIL_SPAM_STATUS}
  target-email: ${EMAIL_TARGET_EMAIL}
  scheduled_hour_cron: ${SCHEDULED_HOUR_CRON}
jwt:
  secret: ${JWT_SECRET}