name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven (without tests)
        run: mvn clean package

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          EMAIL_SPAM_STATUS: ${{ secrets.EMAIL_SPAM_STATUS }}
          EMAIL_TARGET_EMAIL: ${{ secrets.EMAIL_TARGET_EMAIL }}
          SCHEDULED_HOUR_CRON: ${{ secrets.SCHEDULED_HOUR_CRON }}
        run: |
          flyctl deploy --build-arg DB_HOST=${{ env.DB_HOST }} \
                        --build-arg DB_PORT=${{ env.DB_PORT }} \
                        --build-arg DB_NAME=${{ env.DB_NAME }} \
                        --build-arg DB_USERNAME=${{ env.DB_USERNAME }} \
                        --build-arg DB_PASSWORD=${{ env.DB_PASSWORD }}
