name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven (without tests)
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly.io
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          EMAIL_SPAM_STATUS: ${{ secrets.EMAIL_SPAM_STATUS }}
          EMAIL_TARGET_EMAIL: ${{ secrets.EMAIL_TARGET_EMAIL }}
          SCHEDULED_HOUR_CRON: ${{ secrets.SCHEDULED_HOUR_CRON }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
        run: |
          flyctl deploy -a $FLY_APP_NAME --image myapp
