name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          JDBC_DATABASE_URL: ${{ env.SPRING_DATASOURCE_URL }}
          JDBC_DATABASE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          JDBC_DATABASE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
          EMAIL_SPAM_STATUS: ${{ secrets.EMAIL_SPAM_STATUS }}
          EMAIL_TARGET_EMAIL: ${{ secrets.EMAIL_TARGET_EMAIL }}
          SCHEDULED_HOUR_CRON: ${{ secrets.SCHEDULED_HOUR_CRON }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku auth:token
          heroku plugins:install java
          heroku deploy:jar target/emailserver-0.0.1-SNAPSHOT.jar --app serveremail

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Andresdavid2310_emailserver \
            -Dsonar.organization=benavides \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}