name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ JDBC_DATABASE_URL }}
      DB_PORT: ${{ DB_PORT }}
      DB_NAME: ${{ JDBC_DATABASE_NAME }}
      DB_USERNAME: ${{ JDBC_DATABASE_USERNAME }}
      DB_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
      SPRING_DATASOURCE_URL: ${{ JDBC_DATABASE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ JDBC_DATABASE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_SPAM_STATUS: ${{ env.EMAIL_SPAM_STATUS }}
      EMAIL_TARGET_EMAIL: ${{ env.EMAIL_TARGET_EMAIL }}
      SCHEDULED_HOUR_CRON: ${{ env.SCHEDULED_HOUR_CRON }}

    steps:
      - name: Debug Print Environment Variables
        run: |
          echo "SPRING_DATASOURCE_URL: ${{SPRING_DATASOURCE_URL}}"
          echo "SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME"
          echo "SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD"
          echo "DB_HOST: $DB_HOST"
          echo "DB_PORT: $DB_PORT"
          echo "DB_NAME: $DB_NAME"
          echo "DB_USERNAME: $DB_USERNAME"
          echo "DB_PASSWORD: $DB_PASSWORD"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven (without tests)
        run: mvn clean package

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --build-arg DB_HOST=${{ env.DB_HOST }} \
                        --build-arg DB_PORT=${{ env.DB_PORT }} \
                        --build-arg DB_NAME=${{ env.DB_NAME }} \
                        --build-arg DB_USERNAME=${{ env.DB_USERNAME }} \
                        --build-arg DB_PASSWORD=${{ env.DB_PASSWORD }}
